# Generated by Django 3.2.8 on 2022-04-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_sys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('create_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
