# Generated by Django 3.2.8 on 2022-04-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_sys', '0003_alter_notification_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='create_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
