# Generated by Django 3.2.8 on 2022-04-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu_sys', '0004_alter_notification_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='detail',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
